import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const session = useSession();
  console.log(session);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session.data?.user ? (
        <button
          onClick={() => {
            void signOut();
          }}
        >
          Wyloguj
        </button>
      ) : (
        <Link href="/zaloguj">Login</Link>
      )}
    </>
  );
};

export default Home;
